--@autor:           Juárez Pérez Hugo
--@Fecha creación:  2021-12-28
--@Descripción:     Script para realizar la carga inicial todas las tablas de la base de datos.ABORT

--TODO:
--Llenar con datos de mockaroo xd
--CAMBIAR A TIPOS DE DATOS VALIDOS los booleanos

connect rj_proy_admin/rj_admin
set serveroutput on 
 
prompt Llenando datos para cliente

--Cliente  (100 registros)
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (1, 'Salome', 'Halwell', 'Swinburn', '8591 Pleasure Park', 'sswinburn0', 'QhapS7');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (2, 'Leoline', 'Abramski', 'Edser', '16 Onsgard Plaza', 'ledser1', 'n4XB1ESWfiR');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (3, 'Engelbert', 'Skitch', 'Estabrook', '03 Di Loreto Way', 'eestabrook2', '0nByQ3pRlEqI');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (4, 'Salomi', 'Atkirk', 'Windows', '820 Oak Valley Crossing', 'swindows3', 'hgdhQsl');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (5, 'Bettina', 'Habbershon', 'Simes', '67598 Northland Drive', 'bsimes4', '0Qrq40');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (6, 'Thornie', 'Wride', 'Breston', '527 Nobel Hill', 'tbreston5', '0Uu6kQEW1DQQ');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (7, 'Amalia', 'Cant', 'Lawrey', '66 Superior Parkway', 'alawrey6', 'ReIIum');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (8, 'Sharity', 'Grimsdyke', 'Tibbetts', '7 Center Road', 'stibbetts7', 'PVmpXJ0');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (9, 'Jude', 'Bamsey', 'Gillean', '8870 Oak Crossing', 'jgillean8', 'XxZ5buz');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (10, 'Vernen', 'Golsby', 'Di Lucia', '99 Forest Run Center', 'vdilucia9', 'D7LxtB2Biu');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (11, 'Dunn', 'Kernaghan', 'Ziemecki', '34 Havey Street', 'dziemeckia', 'ZreVFlv');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (12, 'Eliza', 'Mazin', 'Chavey', '85952 Mendota Point', 'echaveyb', 'K3LS9HIc8t');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (13, 'Kellen', 'McLean', 'Staggs', '6919 Fordem Lane', 'kstaggsc', 'Z2ZOLvx8');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (14, 'Elle', 'Craven', 'Titchener', '439 Sunbrook Avenue', 'etitchenerd', '94BSbjrI');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (15, 'Editha', 'Pillinger', 'Zanetto', '614 Ridgeview Way', 'ezanettoe', '9zJWYL');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (16, 'Lorens', 'Beecroft', 'Vermer', '72 Brentwood Pass', 'lvermerf', 'qGSlfPlR');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (17, 'Adrea', 'Cade', 'Havik', '7540 Independence Hill', 'ahavikg', 'cgP1uj');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (18, 'Farrell', 'Heindrick', 'Hickisson', '280 Sherman Drive', 'fhickissonh', 'XkohWEjOSmD');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (19, 'Lolita', 'Kinnin', 'Gooms', '74 American Ash Circle', 'lgoomsi', 'aImgjigGH');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (20, 'Jada', 'Urwen', 'Touhig', '14 Lillian Hill', 'jtouhigj', 'e2JuqUdybh');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (21, 'Cally', 'Moat', 'Dowthwaite', '5642 Pond Center', 'cdowthwaitek', '2dW64k9gk3RX');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (22, 'Marlowe', 'Sandland', 'Hawkridge', '36 Sachs Circle', 'mhawkridgel', 'esrOHznk');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (23, 'Cornell', 'Smart', 'Burkinshaw', '50641 Springs Street', 'cburkinshawm', 'ByyUPjjjxY');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (24, 'Weidar', 'Mandrake', 'Fortman', '395 Sachs Court', 'wfortmann', 'fMbDZDBas8K');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (25, 'Janice', 'Hadleigh', 'Gilmartin', '1520 Dottie Pass', 'jgilmartino', 'kruxybok');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (26, 'Beverlie', 'Postans', 'Tumini', '2 Hollow Ridge Lane', 'btuminip', 'P3cqblvD');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (27, 'Massimiliano', 'Broadey', 'Pomfrey', '72 Anzinger Lane', 'mpomfreyq', 'qlA5z1TBo8Lw');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (28, 'Tabby', 'Shwenn', 'Van Oort', '13 Stang Avenue', 'tvanoortr', '691HMJqwQw');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (29, 'Marcelo', 'Gosnold', 'Wyndham', '74 Monterey Court', 'mwyndhams', 'zjreoLLtkxLi');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (30, 'Marquita', 'Gladdor', 'Boxell', '268 Eastwood Place', 'mboxellt', 'jqJiJ0r1');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (31, 'Joannes', 'Pyett', 'Rangall', '1536 Green Ridge Crossing', 'jrangallu', 'cqxgHK');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (32, 'Blinnie', 'Bertomier', 'Levy', '5642 Walton Road', 'blevyv', 'qKXQmmoz0s0');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (33, 'Cassey', 'Wellstead', 'Higgoe', '86 Oak Valley Court', 'chiggoew', 'Vbaa5t');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (34, 'Petronilla', 'Warnes', 'Saywood', '817 Anderson Hill', 'psaywoodx', 'zsRpfelO');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (35, 'Dolph', 'Dwyr', 'Streets', '93087 Veith Point', 'dstreetsy', 'DA15xE4');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (36, 'Riannon', 'Bitcheno', 'Surman', '897 Bluestem Crossing', 'rsurmanz', '8irF1Dx2');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (37, 'Graig', 'Prys', 'Wilman', '73912 Cody Park', 'gwilman10', 'ZXRqt5lBT1');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (38, 'Gabey', 'China', 'Mosby', '5 Amoth Terrace', 'gmosby11', 'EagzcoeMcCiy');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (39, 'Glyn', 'Fereday', 'Killner', '420 Jana Plaza', 'gkillner12', 'c11wdTB');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (40, 'Oriana', 'Pydcock', 'Edens', '76165 Ridgeway Terrace', 'oedens13', 'qwSSzy');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (41, 'Kristian', 'Baddoe', 'Broad', '66 Ronald Regan Parkway', 'kbroad14', 'xAnYlXr7LW2');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (42, 'Diana', 'Smaling', 'Boak', '4922 Eagle Crest Parkway', 'dboak15', 'fLLt6PwqWFuK');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (43, 'Barnett', 'Cristofori', 'Hollier', '4 Barby Drive', 'bhollier16', 'Uv4BD5Ckr');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (44, 'Carter', 'Obee', 'Danbury', '20935 Duke Drive', 'cdanbury17', 'w8kvnaH');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (45, 'Goldy', 'Gerardet', 'Gomm', '5 Cody Parkway', 'ggomm18', 'rB0qr98V');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (46, 'Deva', 'Restieaux', 'Milesap', '98 Brown Trail', 'dmilesap19', 'x4VAtA');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (47, 'Kayle', 'Eakley', 'Baude', '2 Gerald Place', 'kbaude1a', 'Es3kIxNQFfBd');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (48, 'Dex', 'Falconbridge', 'Yannoni', '2409 Green Ridge Avenue', 'dyannoni1b', 'ne8n5eCP4DR');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (49, 'Hillel', 'Barrus', 'Iseton', '1082 Forest Dale Lane', 'hiseton1c', 'KodEBB5Fe');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (50, 'Elwyn', 'Larder', 'Ariss', '00 Swallow Terrace', 'eariss1d', 'szSEfbpiw');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (51, 'Clarice', 'O''Dougherty', 'Rilton', '291 Havey Avenue', 'crilton1e', 'SDYPy0NYOSpg');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (52, 'Marlyn', 'Balderstone', 'Szachniewicz', '4 Mallard Place', 'mszachniewicz1f', 'jlm1Wg7J');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (53, 'Billy', 'D''Alwis', 'Eades', '197 Moulton Place', 'beades1g', 'yi2oj5');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (54, 'Tawnya', 'Manicom', 'Wakefield', '38896 Farwell Road', 'twakefield1h', 't3rFBLCoMCf');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (55, 'Jamey', 'Matousek', 'Tschiersch', '334 Stephen Trail', 'jtschiersch1i', 'IBj66TtlNrg');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (56, 'Cord', 'Donnison', 'Charlo', '44 Marcy Street', 'ccharlo1j', 'CpeMYEi7K2KT');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (57, 'Isabeau', 'Pidon', 'Haldene', '66 Steensland Alley', 'ihaldene1k', '4jbYJ1');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (58, 'Penrod', 'Bust', 'Brisland', '38 Lunder Junction', 'pbrisland1l', 'ha7om6K');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (59, 'Reinwald', 'Sonschein', 'Di Iorio', '3096 International Parkway', 'rdiiorio1m', 'xIclEPEq');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (60, 'Margarethe', 'Jacklin', 'Coper', '74 Monument Pass', 'mcoper1n', 'VWYSxkbqwf');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (61, 'Robinett', 'Krzyzanowski', 'Arnoll', '703 Pepper Wood Trail', 'rarnoll1o', 'KSt6Ek');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (62, 'Cherida', 'Giacopazzi', 'Cursey', '78 Prairie Rose Drive', 'ccursey1p', 'p0QaNxwm');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (63, 'Shirlee', 'Pablos', 'Stockhill', '69 Esch Court', 'sstockhill1q', '70U6rqOeVn');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (64, 'Felisha', 'Millbank', 'Rainy', '963 Hanover Point', 'frainy1r', 'oZ6tSGNjhitI');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (65, 'Antonietta', 'Jerams', 'Whysall', '56 Hooker Center', 'awhysall1s', 'Uh0axP');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (66, 'Carmen', 'Seagrove', 'Espada', '85 Goodland Drive', 'cespada1t', 'RPI8eY0A60Ra');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (67, 'Hyacinthe', 'Leek', 'Peizer', '32 Scofield Court', 'hpeizer1u', 'RVCsErg5q');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (68, 'Jeff', 'O''Regan', 'Laverty', '3 Onsgard Lane', 'jlaverty1v', 'Sx2Dy4t0S7N');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (69, 'Lenard', 'Double', 'Bliven', '87493 Cambridge Way', 'lbliven1w', 'qeIyY9Uy');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (70, 'Marice', 'Pantecost', 'Sharman', '7 Alpine Alley', 'msharman1x', '2dtvyq');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (71, 'Dniren', 'MacInherney', 'Lamy', '250 Pierstorff Alley', 'dlamy1y', 'oRhPbU');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (72, 'Koral', 'Adamovsky', 'Tebbett', '1260 Northfield Circle', 'ktebbett1z', 'E19HcZ');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (73, 'Amandi', 'Honsch', 'Weatherill', '7866 Del Sol Road', 'aweatherill20', 'BeF2uO41K');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (74, 'Desmund', 'De La Coste', 'Fluck', '3872 Marcy Point', 'dfluck21', 'JXZIxAlChrg');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (75, 'Noby', 'Woodvine', 'Coombe', '7 Mallory Hill', 'ncoombe22', 'nb9ER1ANO');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (76, 'Carola', 'Herreran', 'Claiton', '60787 Sunfield Park', 'cclaiton23', 'e396WsGUS');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (77, 'Clayson', 'Dew', 'Delucia', '9286 American Ash Street', 'cdelucia24', 'UZMFHl');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (78, 'Car', 'Duquesnay', 'Simonin', '82098 Aberg Drive', 'csimonin25', 'VP3WyhTo');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (79, 'Kendra', 'Steade', 'Croux', '458 Blue Bill Park Parkway', 'kcroux26', 'c2rGey');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (80, 'Mellisa', 'MacMechan', 'McAreavey', '71 Michigan Park', 'mmcareavey27', 'C3CioF06px');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (81, 'Patience', 'Rosendorf', 'Tyrrell', '913 Old Shore Road', 'ptyrrell28', 'QqHdlkAYNDDd');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (82, 'Gisella', 'Brunskill', 'Noods', '16333 Lakeland Avenue', 'gnoods29', 'DFVwiUk');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (83, 'Gerianna', 'Chattey', 'Archer', '686 Grover Alley', 'garcher2a', 'mspcwSwEz5YY');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (84, 'Shirley', 'Dalla', 'Worsham', '21617 Village Park', 'sworsham2b', 'H4TaUMfNcE');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (85, 'Tamarah', 'Bazoche', 'Pierri', '44 7th Circle', 'tpierri2c', 'm90dnimAfg');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (86, 'Tab', 'Kynder', 'Casero', '41288 Packers Junction', 'tcasero2d', 'PfOB9v2I9');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (87, 'Gratiana', 'Marflitt', 'Bodiam', '8411 Michigan Alley', 'gbodiam2e', 'Sq0Kb7');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (88, 'Ingaborg', 'Largen', 'Cready', '7574 Lillian Terrace', 'icready2f', 'OMTh8SNzSf');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (89, 'Gherardo', 'Spottswood', 'Fruin', '0745 Roth Center', 'gfruin2g', 'WKglRRHgi');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (90, 'Sonja', 'Spradbrow', 'Ewbanke', '68247 Brentwood Center', 'sewbanke2h', 'p8wAv4');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (91, 'Kerry', 'Yosifov', 'Norcross', '071 Sunnyside Pass', 'knorcross2i', 'fYrEa6ob');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (92, 'Chad', 'Stobbs', 'Loveard', '5 Reindahl Point', 'cloveard2j', 'NOmV9S');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (93, 'Bettina', 'Langdridge', 'Larvor', '424 Fieldstone Hill', 'blarvor2k', 'EBJksGRnMdx');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (94, 'Bernelle', 'Gabriel', 'Klemencic', '7 5th Trail', 'bklemencic2l', 'BZl6926T0b');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (95, 'Osgood', 'McCloughlin', 'Von Gladbach', '92923 Warrior Way', 'ovongladbach2m', 'nVeGSNKXW');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (96, 'Melba', 'Heindrich', 'Woolfoot', '05 Mariners Cove Terrace', 'mwoolfoot2n', 'Wic5pM');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (97, 'Eustacia', 'Greschke', 'Fashion', '650 Eastlawn Way', 'efashion2o', 'K7JNwMx');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (98, 'Obediah', 'Navein', 'Gerbl', '9382 Green Way', 'ogerbl2p', 'ZoW1Ew9JIaE');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (99, 'Agneta', 'Bentame', 'Siemantel', '658 Becker Lane', 'asiemantel2q', '2FdMAsy9WRkt');
insert into cliente (cliente_id, nombre, ap_paterno, ap_materno, direccion, usuario, contraseña) values (100, 'Maisie', 'Tschierasche', 'Bonafant', '536 Rigney Plaza', 'mbonafant2r', 'qiAdin3eC');


--Mascota


--Adopcion

--Centro operativo


--Empleado
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (1, 'Deonne', 'Langhorn', 'Truter', 26211.09, '4/23/2021', 'dtruter0@reverbnation.com', 'QIZO424229MNEIZR22', false, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (2, 'Dorice', 'Ramsier', 'Scotchmer', 10801.02, '4/13/2021', 'dscotchmer1@tmall.com', 'VUOL735428FYNZER02', true, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (3, 'Blinni', 'Martensen', 'Hallums', 28750.01, '1/27/2021', 'bhallums2@miibeian.gov.cn', 'UUHP441216FNEAJA92', false, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (4, 'Britt', 'Goodisson', 'Tomczak', 29275.72, '5/29/2021', 'btomczak3@elpais.com', 'MUDU950717MNERCJ22', true, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (5, 'Nertie', 'Hartley', 'Maier', 31282.77, '12/14/2021', 'nmaier4@goodreads.com', 'BOTF652180FNEROC82', true, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (6, 'Jordanna', 'Hallgath', 'Chasier', 10832.87, '6/1/2021', 'jchasier5@hibu.com', 'SADG196009FYNHYY42', true, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (7, 'Cissiee', 'Veal', 'Busch', 11247.35, '11/10/2021', 'cbusch6@webnode.com', 'JUVK965841MNEIST92', true, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (8, 'Rex', 'Dowzell', 'Franken', 9467.82, '1/3/2021', 'rfranken7@twitter.com', 'QUFF579476MYNNAV82', true, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (9, 'Orelee', 'Slides', 'Wharlton', 23058.22, '7/20/2021', 'owharlton8@tamu.edu', 'IOQK185010FNEEOR62', false, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (10, 'Gage', 'Poznanski', 'Crooks', 12274.06, '8/10/2021', 'gcrooks9@samsung.com', 'OUES414455MNECQW42', true, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (11, 'Alwyn', 'Jorin', 'Simonini', 32997.29, '6/20/2021', 'asimoninia@barnesandnoble.com', 'MUOV861845FYNKLX72', true, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (12, 'Prissie', 'Wilden', 'Kitchenside', 33243.14, '9/8/2021', 'pkitchensideb@spiegel.de', 'MONM242965MZSAEA92', false, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (13, 'Grove', 'Stubbert', 'Vitet', 27147.36, '2/2/2021', 'gvitetc@printfriendly.com', 'VUOG646476MNEKTV32', true, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (14, 'Abigael', 'Cianni', 'Mowsdell', 20788.66, '5/12/2021', 'amowsdelld@networksolutions.com', 'HUNR813567MZSWZK82', false, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (15, 'Thomas', 'Sayburn', 'Wraxall', 7831.13, '1/27/2021', 'twraxalle@purevolume.com', 'TISE110680MNERTL32', false, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (16, 'Chloe', 'MacAdam', 'Morris', 29530.1, '12/6/2021', 'cmorrisf@google.com.au', 'YUSJ490650FZSQIT02', true, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (17, 'Shermie', 'Mayhew', 'Griffithe', 27326.72, '1/31/2021', 'sgriffitheg@constantcontact.com', 'YUAD326674FNEOEH62', false, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (18, 'Jory', 'Morrel', 'Zanuciolii', 14854.16, '4/12/2021', 'jzanucioliih@qq.com', 'IUSI508398FNEXLP42', false, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (19, 'Trefor', 'Arghent', 'Grindle', 20756.81, '5/3/2021', 'tgrindlei@columbia.edu', 'MIXD280626MNEUUH62', true, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (20, 'Cynthie', 'Laughrey', 'Matteoli', 27259.57, '4/8/2021', 'cmatteolij@mac.com', 'CUYI674767FNENIK82', false, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (21, 'Brockie', 'Cloutt', 'Popeley', 30430.38, '6/24/2021', 'bpopeleyk@sbwire.com', 'IIGK176324FZSEGE12', true, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (22, 'Irena', 'Dabner', 'Pratte', 13367.69, '1/20/2021', 'iprattel@github.io', 'WOSP578394FZSWNM72', false, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (23, 'Torrance', 'Blain', 'Gager', 17273.03, '12/19/2021', 'tgagerm@google.ca', 'HUBQ957823FZSKNS72', true, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (24, 'Jean', 'Loades', 'Steeden', 24297.5, '6/5/2021', 'jsteedenn@t-online.de', 'PUEN004101FNENLM02', false, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (25, 'Ive', 'Sleep', 'Gowen', 23026.5, '7/31/2021', 'igoweno@whitehouse.gov', 'UAXA294196MNEGAD52', false, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (26, 'Karrah', 'Geck', 'Grandison', 13461.72, '8/24/2021', 'kgrandisonp@imageshack.us', 'VUJV689348FYNXWP22', true, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (27, 'Hestia', 'Meysham', 'Schwartz', 19151.57, '2/15/2021', 'hschwartzq@upenn.edu', 'TEIY360213FNESCK22', true, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (28, 'Renaud', 'Mundle', 'Sellack', 20202.04, '7/17/2021', 'rsellackr@slate.com', 'OUDG684069FNECDR12', false, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (29, 'Pat', 'Studders', 'Simecek', 11024.04, '3/1/2021', 'psimeceks@tmall.com', 'BOOO873442MNEHIF82', false, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (30, 'Blair', 'Surcomb', 'Morsom', 33479.93, '9/3/2021', 'bmorsomt@cdbaby.com', 'KESE188299MVZFCD52', true, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (31, 'Gerrie', 'Dibsdale', 'Aguirrezabala', 33882.52, '11/9/2021', 'gaguirrezabalau@com.com', 'HORA933268FYNZXY02', true, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (32, 'Alfonso', 'Roderham', 'McRannell', 31871.39, '7/24/2021', 'amcrannellv@abc.net.au', 'REWV659424MNEZDZ72', true, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (33, 'Artemis', 'Noblet', 'Dene', 13428.76, '10/8/2021', 'adenew@infoseek.co.jp', 'AUWR999644MNEEVQ42', true, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (34, 'Angelita', 'Rohlfs', 'D''Aguanno', 31576.41, '4/13/2021', 'adaguannox@engadget.com', 'JOOQ441508FVZBFT72', false, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (35, 'Chantalle', 'Juschka', 'Davys', 16234.87, '10/2/2021', 'cdavysy@eepurl.com', 'POQH118266FVZDED52', false, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (36, 'Normy', 'Woodroofe', 'Tink', 12024.3, '5/4/2021', 'ntinkz@dot.gov', 'HUGD368601MNESWS92', false, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (37, 'Sergeant', 'Arstingall', 'Alvy', 11246.08, '3/15/2021', 'salvy10@smugmug.com', 'CORD567488FYNBIR52', false, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (38, 'Noelyn', 'Tidmarsh', 'Schutte', 12314.49, '4/20/2021', 'nschutte11@theatlantic.com', 'HOYK709221MNEFKL42', false, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (39, 'Putnam', 'Andraud', 'Brucker', 21770.87, '10/23/2021', 'pbrucker12@hc360.com', 'MOHW246149MNEISG62', false, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (40, 'Celestine', 'Murrow', 'Fibbitts', 18634.84, '8/13/2021', 'cfibbitts13@spiegel.de', 'SOVC369771FYNXYE52', false, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (41, 'Lorene', 'Flippen', 'Peller', 28549.66, '6/19/2021', 'lpeller14@ebay.com', 'AULL811720MYNMDF12', true, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (42, 'Adriena', 'Delany', 'Macbane', 19452.93, '6/24/2021', 'amacbane15@ycombinator.com', 'XIUK024808MNEPZB02', true, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (43, 'Maxy', 'Vamplew', 'Mussington', 11738.39, '8/19/2021', 'mmussington16@wikipedia.org', 'VEUT280541MNEHCU72', true, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (44, 'Merwyn', 'McRavey', 'Gwinn', 7915.81, '12/10/2021', 'mgwinn17@mac.com', 'WUEK712945FNENKF32', true, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (45, 'Edwin', 'Pottell', 'Warrington', 26738.2, '6/26/2021', 'ewarrington18@stanford.edu', 'EODQ672525FYNKHP62', false, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (46, 'Libbi', 'Dodding', 'Dominici', 23049.79, '7/21/2021', 'ldominici19@psu.edu', 'EUNA251214FZSPMW52', true, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (47, 'Jyoti', 'Kloster', 'Pawelski', 25154.05, '7/10/2021', 'jpawelski1a@toplist.cz', 'COLF700798MZSHLN32', true, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (48, 'Minda', 'Orpwood', 'MacCallion', 27813.77, '12/29/2020', 'mmaccallion1b@bizjournals.com', 'OOLB810392FNEEVD62', false, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (49, 'Eden', 'Puffett', 'Porte', 27168.4, '7/8/2021', 'eporte1c@aboutads.info', 'SUGH552406MNEKDH72', false, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (50, 'Thomasine', 'Lindfors', 'Slemmonds', 23871.31, '5/14/2021', 'tslemmonds1d@prlog.org', 'CUZP672801FNECIM22', true, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (51, 'Jenda', 'Aupol', 'Riddett', 15937.89, '12/26/2021', 'jriddett1e@bbb.org', 'KUDN727708FNEGPN32', false, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (52, 'Elvira', 'Tunnadine', 'Burleigh', 22777.14, '12/13/2021', 'eburleigh1f@answers.com', 'KUDW632516MNEPPC12', true, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (53, 'Lynsey', 'Chedzoy', 'Joslyn', 12444.26, '8/30/2021', 'ljoslyn1g@feedburner.com', 'HONS924479MNEXIU92', true, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (54, 'Laurie', 'Marin', 'Shields', 22440.84, '10/22/2021', 'lshields1h@spotify.com', 'WIZR394413FZSPHF72', false, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (55, 'Garald', 'Kibbee', 'Yeoman', 7014.77, '5/18/2021', 'gyeoman1i@yahoo.co.jp', 'COMB058072FNEZRU02', false, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (56, 'Bern', 'Weinham', 'Slaght', 17351.21, '8/25/2021', 'bslaght1j@npr.org', 'GOXK357430FTLGKW32', true, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (57, 'Cordey', 'Henrionot', 'Ausher', 11821.63, '8/28/2021', 'causher1k@gov.uk', 'QUZO247223MZSNHZ62', true, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (58, 'Carney', 'Gallety', 'Dohmann', 27166.9, '5/22/2021', 'cdohmann1l@bloglines.com', 'SUFE840716MTSWGI32', false, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (59, 'Terrell', 'Guillond', 'Philpot', 7052.98, '10/18/2021', 'tphilpot1m@networksolutions.com', 'KECZ380376MZSJHG82', false, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (60, 'Cassey', 'Werrett', 'Fridaye', 34820.19, '12/4/2021', 'cfridaye1n@tmall.com', 'MUDR044549FNEEFM82', true, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (61, 'Loralyn', 'Halleybone', 'McBoyle', 9340.91, '10/9/2021', 'lmcboyle1o@fda.gov', 'WORI279200MTSYIO42', true, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (62, 'Tremayne', 'Hrishchenko', 'McInally', 31984.46, '12/12/2021', 'tmcinally1p@pcworld.com', 'PUXP722582FYNKBJ32', true, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (63, 'Kristofer', 'Bluett', 'Ivanishchev', 22380.3, '4/9/2021', 'kivanishchev1q@blinklist.com', 'TIJG693165MNEDXW22', true, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (64, 'Fiona', 'Boullen', 'Shearsby', 27292.4, '4/12/2021', 'fshearsby1r@archive.org', 'QITV141792FNEYOE12', true, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (65, 'Ariel', 'Wayt', 'Blundin', 13289.26, '2/12/2021', 'ablundin1s@quantcast.com', 'UUHT419344FYNKQK72', false, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (66, 'Regan', 'Dumphreys', 'Chance', 15259.12, '2/5/2021', 'rchance1t@com.com', 'IULF572457MNEVBN72', false, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (67, 'Hazel', 'Filshin', 'Uccelli', 13243.27, '5/15/2021', 'huccelli1u@geocities.com', 'PUEB312637FZSWEU92', true, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (68, 'Lion', 'Paxeford', 'Wantling', 7604.45, '8/25/2021', 'lwantling1v@chronoengine.com', 'HAIO407013FNEHNY52', true, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (69, 'Emmaline', 'Fermin', 'Beynkn', 16929.88, '9/27/2021', 'ebeynkn1w@xinhuanet.com', 'ROGK053427FNEODE62', false, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (70, 'Jenda', 'Sprowles', 'Whittlesee', 9603.55, '10/4/2021', 'jwhittlesee1x@pinterest.com', 'UONB074558MYNQDM62', true, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (71, 'Allister', 'Donnersberg', 'Gleadle', 24701.43, '2/28/2021', 'agleadle1y@google.nl', 'UUHZ393680MNEGXT12', false, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (72, 'Ailene', 'Atchly', 'Scaddon', 25394.01, '2/2/2021', 'ascaddon1z@columbia.edu', 'QUGA708921MNEUKU32', true, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (73, 'Billie', 'Marquess', 'Swaine', 14822.68, '9/30/2021', 'bswaine20@dell.com', 'KUSF945821MNEEXH42', false, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (74, 'Robinson', 'Anger', 'Dankersley', 34568.76, '10/10/2021', 'rdankersley21@sohu.com', 'TOXF152015MNERIB42', true, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (75, 'Lennie', 'Haestier', 'Margett', 29445.29, '6/22/2021', 'lmargett22@aol.com', 'NUDC115055MNEVXN92', false, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (76, 'Jarvis', 'Rosenstengel', 'Trotman', 11750.33, '2/6/2021', 'jtrotman23@wunderground.com', 'TUMB422109MNEHCW32', false, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (77, 'Constantine', 'Golson', 'Lagen', 19766.37, '1/18/2021', 'clagen24@cpanel.net', 'UUHA723855MTLABR72', true, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (78, 'Anabelle', 'Jagielski', 'Toolan', 18798.38, '1/2/2021', 'atoolan25@facebook.com', 'XOIA977963FZSPXB62', true, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (79, 'Selia', 'Linfoot', 'Geistmann', 12884.63, '11/10/2021', 'sgeistmann26@cargocollective.com', 'GUZU524402MNEVKQ22', false, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (80, 'Erik', 'Richards', 'Shopcott', 17193.57, '7/25/2021', 'eshopcott27@go.com', 'EEVC497522FNEGYJ22', false, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (81, 'Myra', 'Minichi', 'Trembey', 25776.7, '3/29/2021', 'mtrembey28@livejournal.com', 'AUKP056413MVZGQR62', true, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (82, 'Mada', 'Jockle', 'Lawrey', 28620.58, '2/11/2021', 'mlawrey29@imgur.com', 'FUNV302622FYNMJQ42', true, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (83, 'Caldwell', 'Janic', 'Fortune', 26343.26, '10/15/2021', 'cfortune2a@washingtonpost.com', 'SAUV148183MNEXOM82', true, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (84, 'Cordy', 'Pottage', 'Stopp', 21302.24, '3/4/2021', 'cstopp2b@quantcast.com', 'KAAN239862FNEMOM42', true, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (85, 'Opal', 'Lynock', 'Uzzell', 12731.53, '7/4/2021', 'ouzzell2c@surveymonkey.com', 'SUTY628921FZSFXX92', true, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (86, 'Park', 'Gyles', 'Rubinovitsch', 20235.83, '12/5/2021', 'prubinovitsch2d@nbcnews.com', 'HUSR473271MZSZAT52', false, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (87, 'Oswald', 'Bertin', 'Kearsley', 32384.77, '6/6/2021', 'okearsley2e@census.gov', 'PEOZ522152MNERMQ12', false, true, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (88, 'Concordia', 'Elecum', 'Shilladay', 7551.32, '5/31/2021', 'cshilladay2f@quantcast.com', 'SUOD707192MZSXCM92', true, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (89, 'Ernst', 'Kelloch', 'Hastelow', 21077.59, '11/6/2021', 'ehastelow2g@hhs.gov', 'MARH515936MYNKTD12', true, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (90, 'Carlyn', 'Chopy', 'Lulham', 22253.26, '8/5/2021', 'clulham2h@livejournal.com', 'EIBE363795MNEFEI72', false, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (91, 'Vita', 'Geerling', 'Tice', 16324.11, '10/13/2021', 'vtice2i@nps.gov', 'FOLI531745FNEBXX92', false, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (92, 'Guinna', 'Lambie', 'Setterington', 19875.07, '8/19/2021', 'gsetterington2j@bing.com', 'YOPW476242FZSDVC42', true, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (93, 'Nate', 'Weeke', 'Chadbourne', 33774.68, '10/4/2021', 'nchadbourne2k@mashable.com', 'AOTQ169599MYNDFG42', true, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (94, 'Rance', 'Cutmare', 'Kaufman', 26118.88, '5/25/2021', 'rkaufman2l@bluehost.com', 'UUUS886776FZSBBE72', false, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (95, 'Joachim', 'Strickett', 'Gabby', 10776.14, '4/7/2021', 'jgabby2m@photobucket.com', 'BIYE544847FZSRQE12', false, true, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (96, 'Brenn', 'Thornewell', 'Paladini', 9416.25, '2/20/2021', 'bpaladini2n@naver.com', 'VEBP719217MNESLI72', true, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (97, 'Allene', 'Jerdein', 'Petticrew', 30853.75, '8/8/2021', 'apetticrew2o@theatlantic.com', 'YUPY928406MNENSS12', false, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (98, 'Barney', 'Marchant', 'Holgan', 30308.15, '5/5/2021', 'bholgan2p@miibeian.gov.cn', 'EEPX633436MNEQIA02', false, false, true);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (99, 'Robby', 'Rue', 'Lethcoe', 21887.85, '3/7/2021', 'rlethcoe2q@deviantart.com', 'NUUV599772MNEMKI82', false, false, false);
insert into empleado (empleado_id, nombre, ap_paterno, ap_materno, sueldo_mensual, fecha_ingreso, email, CURP, es_veterinario, es_gerente, es_administrativo) values (100, 'Lancelot', 'Farnin', 'Turland', 16277.32, '6/7/2021', 'lturland2r@miibeian.gov.cn', 'UOYW303401MYNMDP42', true, true, false);




--Grado academico

--


